"""PlanApprovalScreen — full-screen modal for reviewing and approving an attack plan."""

from __future__ import annotations

from pathlib import Path
from typing import ClassVar

from rich.text import Text
from textual.app import ComposeResult
from textual.binding import Binding
from textual.containers import Horizontal, Vertical
from textual.screen import ModalScreen
from textual.widgets import Input, Markdown, Static

from nemesis.core.plan_writer import step_preview_markdown
from nemesis.db.models import AttackPlan

_AGENT_COLORS: dict[str, str] = {
    "recon_agent": "#00d4ff",
    "scanning_agent": "#ffd700",
    "enum_agent": "#ff9500",
    "vuln_agent": "#ff2040",
    "enumeration_agent": "#ff9500",
    "ffuf_agent": "#f48c06",
    "vulnerability_agent": "#ff2040",
    "nuclei_agent": "#ff9500",
}


class PlanApprovalScreen(ModalScreen[AttackPlan | None]):
    """Full-screen plan review modal shown after PlannerAgent generates a plan.

    Returns the (possibly edited) AttackPlan on approval or None on cancel.
    """

    BINDINGS: ClassVar[list[Binding]] = [
        Binding("a", "approve", "Approve & Run"),
        Binding("enter", "approve", "Approve & Run", show=False),
        Binding("e", "edit_step", "Edit Step"),
        Binding("d", "delete_step", "Delete Step"),
        Binding("x", "cancel_plan", "Cancel"),
        Binding("escape", "cancel_plan", "Cancel", show=False),
        Binding("up", "move_up", "Move Up", show=False),
        Binding("down", "move_down", "Move Down", show=False),
    ]

    DEFAULT_CSS = """
    PlanApprovalScreen {
        align: center middle;
    }

    PlanApprovalScreen #approval-dialog {
        background: #0f0f1a;
        border: tall #1a1a3a;
        width: 95%;
        height: 88%;
        max-width: 120;
        max-height: 48;
        padding: 0;
    }

    PlanApprovalScreen #approval-header {
        background: #0a0a0a;
        border-bottom: tall #1a1a3a;
        padding: 1 2;
        height: auto;
    }

    PlanApprovalScreen #approval-body {
        height: 1fr;
        min-height: 12;
    }

    PlanApprovalScreen #approval-left {
        width: 38%;
        min-width: 24;
        border-right: tall #1a1a3a;
        padding: 0 1;
    }

    PlanApprovalScreen #approval-steps {
        height: 1fr;
        overflow-y: auto;
        padding: 1 0;
    }

    PlanApprovalScreen #approval-preview {
        width: 1fr;
        min-width: 28;
        padding: 0 1;
    }

    PlanApprovalScreen #approval-markdown {
        height: 1fr;
        overflow-y: auto;
        background: #0a0a0a;
        border: solid #1a1a3a;
        padding: 0 1;
        margin: 1 0;
    }

    PlanApprovalScreen #approval-edit-input {
        background: #0f0f1a;
        border: solid #1a1a3a;
        color: #c8c8d8;
        margin: 0 2 1 2;
        display: none;
    }

    PlanApprovalScreen #approval-footer {
        background: #0a0a0a;
        border-top: tall #1a1a3a;
        padding: 1 2;
        height: auto;
    }
    """

    def __init__(self, plan: AttackPlan, md_path: Path | None = None) -> None:
        super().__init__()
        self._plan = plan
        self._md_path = md_path
        self._selected_idx: int = 0
        self._editing: bool = False

    def compose(self) -> ComposeResult:
        with Vertical(id="approval-dialog"):
            yield Static("", id="approval-header")
            with Horizontal(id="approval-body"):
                with Vertical(id="approval-left"):
                    yield Static("", id="approval-steps")
                with Vertical(id="approval-preview"):
                    yield Markdown("", id="approval-markdown")
            yield Input(
                placeholder="new step name — press enter to confirm",
                id="approval-edit-input",
                disabled=True,
            )
            yield Static("", id="approval-footer")

    def on_mount(self) -> None:
        self.set_focus(None)
        self._render_all()

    # ── Render helpers ─────────────────────────────────────────────────────

    def _render_all(self) -> None:
        self._render_header()
        self._render_steps()
        self._render_briefing_panel()
        self._render_footer()

    def _render_header(self) -> None:
        text = Text()
        text.append("◈ ATTACK PLAN — ", style="bold #00d4ff")
        text.append(self._plan.goal, style="#c8c8d8")
        text.append(
            f"\n  Generated by NEMESIS AI · {len(self._plan.steps)} step(s)",
            style="#555570",
        )
        self.query_one("#approval-header", Static).update(text)

    def _render_steps(self) -> None:
        text = Text()
        if not self._plan.steps:
            text.append("\n  (no steps)\n", style="#ff2040")
            self.query_one("#approval-steps", Static).update(text)
            return

        self._selected_idx = max(0, min(self._selected_idx, len(self._plan.steps) - 1))

        for i, step in enumerate(self._plan.steps):
            agent_color = _AGENT_COLORS.get(step.agent, "#555570")
            tools_str = ", ".join(step.required_tools) if step.required_tools else "—"
            is_selected = i == self._selected_idx

            prefix_icon = "▶ " if is_selected else "  "
            name_style = "bold #ffffff" if is_selected else "#c8c8d8"

            text.append(f"\n  {prefix_icon}", style="#ffd700" if is_selected else "#555570")
            text.append(f"{step.id}  ", style="#555570")
            text.append(step.name, style=name_style)
            text.append(f"  [{step.agent}]", style=agent_color)
            text.append(f"  {tools_str}", style="#555570")

            if step.depends_on:
                text.append(
                    f"\n               depends on: {', '.join(step.depends_on)}",
                    style="italic #555570",
                )

        text.append("\n")
        self.query_one("#approval-steps", Static).update(text)

    def _render_briefing_panel(self) -> None:
        md_widget = self.query_one("#approval-markdown", Markdown)
        if not self._plan.steps:
            md_widget.update("# No steps in plan\n")
            return
        step = self._plan.steps[self._selected_idx]
        md_widget.update(step_preview_markdown(step))

    def _render_footer(self) -> None:
        text = Text()
        text.append("[A] ", style="bold #ffd700")
        text.append("Approve & Run", style="#c8c8d8")
        text.append("    ", style="#555570")
        text.append("[↑/↓] ", style="bold #555570")
        text.append("Select", style="#555570")
        text.append("    ", style="#555570")
        text.append("[E] ", style="bold #00d4ff")
        text.append("Edit Step", style="#c8c8d8")
        text.append("    ", style="#555570")
        text.append("[D] ", style="bold #ff9500")
        text.append("Delete Step", style="#c8c8d8")
        text.append("    ", style="#555570")
        text.append("[X] ", style="bold #ff2040")
        text.append("Cancel", style="#c8c8d8")
        text.append("\n", style="#555570")
        if self._md_path is not None:
            text.append(f"Plan saved: {self._md_path}", style="italic #555570")
        else:
            text.append("Plan file: not saved (see logs)", style="italic #555570")
        self.query_one("#approval-footer", Static).update(text)

    # ── Navigation ──────────────────────────────────────────────────────────

    def action_move_up(self) -> None:
        if self._editing or not self._plan.steps:
            return
        self._selected_idx = max(0, self._selected_idx - 1)
        self._render_steps()
        self._render_briefing_panel()

    def action_move_down(self) -> None:
        if self._editing or not self._plan.steps:
            return
        self._selected_idx = min(len(self._plan.steps) - 1, self._selected_idx + 1)
        self._render_steps()
        self._render_briefing_panel()

    # ── Actions ─────────────────────────────────────────────────────────────

    def action_approve(self) -> None:
        if self._editing:
            return
        if not self._plan.steps:
            return
        self.dismiss(self._plan)

    def action_cancel_plan(self) -> None:
        if self._editing:
            self._cancel_edit()
            return
        self.dismiss(None)

    def action_edit_step(self) -> None:
        if self._editing or not self._plan.steps:
            return
        step = self._plan.steps[self._selected_idx]
        edit_input = self.query_one("#approval-edit-input", Input)
        edit_input.disabled = False
        edit_input.styles.display = "block"
        edit_input.value = step.name
        edit_input.focus()
        self._editing = True

    def action_delete_step(self) -> None:
        if self._editing or not self._plan.steps:
            return
        if len(self._plan.steps) <= 1:
            return
        removed = self._plan.steps.pop(self._selected_idx)
        rid = removed.id
        for s in self._plan.steps:
            s.depends_on = [d for d in s.depends_on if d != rid]
        self._selected_idx = min(self._selected_idx, len(self._plan.steps) - 1)
        self._cancel_edit()
        self._render_all()

    def on_input_submitted(self, event: Input.Submitted) -> None:
        if not self._editing or not self._plan.steps:
            return
        new_name = event.value.strip()
        if new_name:
            self._plan.steps[self._selected_idx].name = new_name
        self._cancel_edit()

    def _cancel_edit(self) -> None:
        edit_input = self.query_one("#approval-edit-input", Input)
        edit_input.styles.display = "none"
        edit_input.disabled = True
        self._editing = False
        self._render_steps()
        self._render_briefing_panel()
        self.set_focus(None)
