"""PlanApprovalScreen — full-screen modal for reviewing and approving an attack plan."""

from __future__ import annotations

from typing import ClassVar

from rich.text import Text
from textual.app import ComposeResult
from textual.binding import Binding
from textual.containers import Vertical
from textual.screen import ModalScreen
from textual.widgets import Input, Static

from nemesis.db.models import AttackPlan

_AGENT_COLORS: dict[str, str] = {
    "recon_agent": "#00d4ff",
    "scanning_agent": "#ffd700",
    "enum_agent": "#ff9500",
    "vuln_agent": "#ff2040",
    "enumeration_agent": "#ff9500",
    "ffuf_agent": "#f48c06",
    "vulnerability_agent": "#ff2040",
}


class PlanApprovalScreen(ModalScreen[AttackPlan | None]):
    """Full-screen plan review modal shown after PlannerAgent generates a plan.

    Returns the (possibly edited) AttackPlan on approval or None on cancel.
    """

    BINDINGS: ClassVar[list[Binding]] = [
        Binding("a", "approve", "Approve & Run"),
        Binding("enter", "approve", "Approve & Run", show=False),
        Binding("e", "edit_step", "Edit Step"),
        Binding("x", "cancel_plan", "Cancel"),
        Binding("escape", "cancel_plan", "Cancel", show=False),
        Binding("up", "move_up", "Move Up", show=False),
        Binding("down", "move_down", "Move Down", show=False),
    ]

    DEFAULT_CSS = """
    PlanApprovalScreen {
        align: center middle;
    }

    #approval-dialog {
        background: #0f0f1a;
        border: tall #1a1a3a;
        width: 74;
        height: auto;
        max-height: 44;
        padding: 0;
    }

    #approval-header {
        background: #0a0a0a;
        border-bottom: tall #1a1a3a;
        padding: 1 2;
        height: auto;
    }

    #approval-steps {
        padding: 1 2;
        height: auto;
        max-height: 28;
        overflow-y: auto;
    }

    #approval-edit-input {
        background: #0f0f1a;
        border: solid #1a1a3a;
        color: #c8c8d8;
        margin: 0 2 1 2;
        display: none;
    }

    #approval-footer {
        background: #0a0a0a;
        border-top: tall #1a1a3a;
        padding: 1 2;
        height: auto;
    }
    """

    def __init__(self, plan: AttackPlan) -> None:
        super().__init__()
        self._plan = plan
        self._selected_idx: int = 0
        self._editing: bool = False

    def compose(self) -> ComposeResult:
        with Vertical(id="approval-dialog"):
            yield Static("", id="approval-header")
            yield Static("", id="approval-steps")
            yield Input(
                placeholder="new step name — press enter to confirm",
                id="approval-edit-input",
                disabled=True,
            )
            yield Static("", id="approval-footer")

    def on_mount(self) -> None:
        self.set_focus(None)
        self._render_all()

    # ── Render helpers ─────────────────────────────────────────────────────

    def _render_all(self) -> None:
        self._render_header()
        self._render_steps()
        self._render_footer()

    def _render_header(self) -> None:
        text = Text()
        text.append("◈ ATTACK PLAN — ", style="bold #00d4ff")
        text.append(self._plan.goal, style="#c8c8d8")
        text.append(
            f"\n  Generated by NEMESIS AI · {len(self._plan.steps)} step(s)",
            style="#555570",
        )
        self.query_one("#approval-header", Static).update(text)

    def _render_steps(self) -> None:
        text = Text()
        for i, step in enumerate(self._plan.steps):
            agent_color = _AGENT_COLORS.get(step.agent, "#555570")
            tools_str = ", ".join(step.required_tools) if step.required_tools else "—"
            is_selected = i == self._selected_idx

            prefix_icon = "▶ " if is_selected else "  "
            name_style = "bold #ffffff" if is_selected else "#c8c8d8"

            text.append(f"\n  {prefix_icon}", style="#ffd700" if is_selected else "#555570")
            text.append(f"{step.id}  ", style="#555570")
            text.append(step.name, style=name_style)
            text.append(f"  [{step.agent}]", style=agent_color)
            text.append(f"  {tools_str}", style="#555570")

            if step.depends_on:
                text.append(
                    f"\n               depends on: {', '.join(step.depends_on)}",
                    style="italic #555570",
                )

        text.append("\n")
        self.query_one("#approval-steps", Static).update(text)

    def _render_footer(self) -> None:
        text = Text()
        text.append("[A] ", style="bold #ffd700")
        text.append("Approve & Run", style="#c8c8d8")
        text.append("    ", style="#555570")
        text.append("[↑/↓] ", style="bold #555570")
        text.append("Select", style="#555570")
        text.append("    ", style="#555570")
        text.append("[E] ", style="bold #00d4ff")
        text.append("Edit Step", style="#c8c8d8")
        text.append("    ", style="#555570")
        text.append("[X] ", style="bold #ff2040")
        text.append("Cancel", style="#c8c8d8")
        self.query_one("#approval-footer", Static).update(text)

    # ── Navigation ──────────────────────────────────────────────────────────

    def action_move_up(self) -> None:
        if self._editing:
            return
        self._selected_idx = max(0, self._selected_idx - 1)
        self._render_steps()

    def action_move_down(self) -> None:
        if self._editing:
            return
        self._selected_idx = min(len(self._plan.steps) - 1, self._selected_idx + 1)
        self._render_steps()

    # ── Actions ─────────────────────────────────────────────────────────────

    def action_approve(self) -> None:
        if self._editing:
            return
        self.dismiss(self._plan)

    def action_cancel_plan(self) -> None:
        if self._editing:
            self._cancel_edit()
            return
        self.dismiss(None)

    def action_edit_step(self) -> None:
        if self._editing or not self._plan.steps:
            return
        step = self._plan.steps[self._selected_idx]
        edit_input = self.query_one("#approval-edit-input", Input)
        edit_input.disabled = False
        edit_input.styles.display = "block"
        edit_input.value = step.name
        edit_input.focus()
        self._editing = True

    def on_input_submitted(self, event: Input.Submitted) -> None:
        if not self._editing or not self._plan.steps:
            return
        new_name = event.value.strip()
        if new_name:
            self._plan.steps[self._selected_idx].name = new_name
        self._cancel_edit()

    def _cancel_edit(self) -> None:
        edit_input = self.query_one("#approval-edit-input", Input)
        edit_input.styles.display = "none"
        edit_input.disabled = True
        self._editing = False
        self._render_steps()
        self.set_focus(None)
